title: ReadLearner
description: A blog offering various useful data
baseurl: /readlearner  # Important for project sites!
url: https://0728george.github.io
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
# Add GA4 later: google_analytics: G-XXXXXXXXXX
